---

- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: Please enter the target host IP/domain separated by comma. (e.g. sandbox-kfk-zk1)
    private: no

  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts


- hosts: dynamically_created_hosts
  vars_prompt:
  - name: zookeeper_id
    prompt: Please enter a zookeeper id(1-256)
    private: no

  become: true
  roles:
    - common
    - java
    - zookeeper
  vars:
    - doc_root: ~/ansible-zookeeper
