---
- name: Setting java update true if required
  set_fact:
    javaUpdateState: latest
  when: updateJava

- name: Install Openjdk | {{ javaVersion }} | OEL 6
  yum:
    name: "{{ item }}"
    state: "{{ javaUpdateState | default('present') }}"
    update_cache: true
  loop:
    - "java-1.{{ javaVersion }}.0-openjdk"
    - "java-1.{{ javaVersion }}.0-openjdk-devel"
